### ISSUE TITLE
English README

### ISSUE THREAD

**Issue by lfarah** [southpeak/ViewStyle#1]
I'd be cool to provide the README in english so everybody in the 🌎 can see it

**Comment by southpeak** [comment]
@lfarah 

Great, just do it. Thank you very much!

**Comment by southpeak** [comment]
@lfarah , I will do that this weekend. Thank you for your advice!

**Comment by southpeak** [comment]
Hi, @lfarah 

I have add README document in english.

**Comment by lfarah** [comment]
thanks!
